from __future__ import annotations

from typing import Protocol

from quant_trade.paper.models import PaperOrder


class Broker(Protocol):
    def get_account(self) -> dict: ...
    def get_positions(self) -> list[dict]: ...
    def submit_order(self, order: PaperOrder) -> PaperOrder: ...
    def cancel_order(self, order_id: str) -> None: ...
    def get_order(self, order_id: str) -> PaperOrder | None: ...
    def list_orders(self) -> list[PaperOrder]: ...
