"""Typed domain models for research backtesting."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SignalSide(StrEnum):
    """Directional intent emitted by a strategy."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class OrderSide(StrEnum):
    """Supported order direction for the long-only simulator."""

    BUY = "buy"
    SELL = "sell"


class Bar(BaseModel):
    """One OHLCV market candle."""

    model_config = ConfigDict(frozen=True)

    timestamp: datetime
    open: float = Field(gt=0)
    high: float = Field(gt=0)
    low: float = Field(gt=0)
    close: float = Field(gt=0)
    volume: float = Field(ge=0)

    @field_validator("high")
    @classmethod
    def high_is_valid(cls, value: float, info: object) -> float:
        return value


class Signal(BaseModel):
    """Strategy output at a timestamp; strength is an optional sizing hint."""

    timestamp: datetime
    side: SignalSide
    strength: float = Field(default=1.0, ge=0.0, le=1.0)
    reason: str = ""


class Order(BaseModel):
    """Requested long-only market order generated by the backtest engine."""

    timestamp: datetime
    side: OrderSide
    quantity: float = Field(gt=0)
    price: float = Field(gt=0)


class Fill(BaseModel):
    """Executed order fill including costs and slippage."""

    timestamp: datetime
    side: OrderSide
    quantity: float = Field(gt=0)
    price: float = Field(gt=0)
    commission: float = Field(default=0.0, ge=0)
    slippage: float = Field(default=0.0, ge=0)


class Position(BaseModel):
    """Current long-only position state."""

    quantity: float = Field(default=0.0, ge=0)
    average_price: float = Field(default=0.0, ge=0)


class Trade(BaseModel):
    """Closed round-trip trade for performance analysis."""

    entry_time: datetime
    exit_time: datetime
    quantity: float = Field(gt=0)
    entry_price: float = Field(gt=0)
    exit_price: float = Field(gt=0)
    pnl: float
    return_pct: float


class PortfolioSnapshot(BaseModel):
    """Point-in-time account state used to build an equity curve."""

    timestamp: datetime
    cash: float
    position_quantity: float = Field(ge=0)
    position_value: float = Field(ge=0)
    equity: float = Field(ge=0)
