"""Build a BYOD audit package skeleton from a customer's own dataset.

The auditor asks a customer to bind their results to their data by SHA-256.
Computing those digests by hand is the single step most likely to be got wrong,
and a wrong digest is indistinguishable from results that were never bound to
the data at all — so the customer gets a ``NO_GO`` for a clerical slip.

This module removes that failure mode.  It reads the customer's dataset bytes,
writes the digests into the two files that must carry them, and leaves every
field that only the customer can know as an explicit ``FILL_ME`` placeholder,
which the auditor then rejects until it is replaced.  It never overwrites an
existing file, never guesses a cost, a benchmark, a licence, or a capture time,
and never touches the network.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from quant_trade.evidence.canonical_json import atomic_write_json, atomic_write_text, sha256_of_file

#: A value the auditor must refuse, so an unfilled template can never pass.
PLACEHOLDER = "FILL_ME"

PACKAGE_FILENAMES: dict[str, str] = {
    "config": "audit.yaml",
    "manifest": "dataset.manifest.json",
    "results": "results.json",
    "trial_ledger": "trial_ledger.json",
}

_DATASET_SUFFIXES = {".csv", ".json", ".jsonl"}

#: What the customer still has to supply, and why the auditor needs it.
REQUIRED_PLACEHOLDERS: tuple[str, ...] = (
    "dataset.manifest.json:source_name — who produced the data",
    "dataset.manifest.json:data_source — the feed or vendor it came from",
    "dataset.manifest.json:captured_at_utc — when you pulled it, at or before the cutoff",
    "dataset.manifest.json:license — your right to use these bytes",
    "results.json:strategy_net_return — net of every cost you declare",
    "results.json:costs.fee_bps / slippage_bps / total_cost_bps — the costs you charged",
    "results.json:execution.signal_lag_bars — bars between decision and fill, at least 1",
    "results.json:benchmarks — at least one net benchmark return to compare against",
    "trial_ledger.json:trials — every variant you evaluated, including the ones you dropped",
)


def _package_paths(package_dir: Path) -> dict[str, Path]:
    return {key: package_dir / name for key, name in PACKAGE_FILENAMES.items()}


def _manifest(dataset: Path, digest: str, cutoff: str) -> dict[str, Any]:
    return {
        "byte_sha256": digest,
        "size_bytes": dataset.stat().st_size,
        "source_name": PLACEHOLDER,
        "data_source": PLACEHOLDER,
        "captured_at_utc": PLACEHOLDER,
        "license": PLACEHOLDER,
        "provenance_notes": PLACEHOLDER,
        "declared_evaluation_cutoff_utc": cutoff,
    }


def _results(digest: str, ledger_digest: str) -> dict[str, Any]:
    return {
        "dataset_sha256": digest,
        "trial_ledger_sha256": ledger_digest,
        "strategy_net_return": PLACEHOLDER,
        "execution": {"signal_lag_bars": PLACEHOLDER},
        "costs": {
            "applied": True,
            "fee_bps": PLACEHOLDER,
            "slippage_bps": PLACEHOLDER,
            "total_cost_bps": PLACEHOLDER,
        },
        "benchmarks": [{"name": PLACEHOLDER, "net_return": PLACEHOLDER}],
    }


def _empty_ledger() -> dict[str, Any]:
    return {"trials": [{"trial_id": PLACEHOLDER}]}


def _config_text(
    *,
    dataset_name: str,
    evaluation_cutoff_utc: str,
    timestamp_column: str,
    symbol_column: str,
) -> str:
    # Written as text rather than dumped, so the customer reads why each key is
    # here.  root_dir stays "." because the auditor refuses a root outside the
    # directory holding the config.
    return (
        "# Generated by `quant-trade audit init`. Paths are relative to this file.\n"
        '# root_dir must stay inside this directory; the auditor rejects "..".\n'
        'root_dir: "."\n'
        f"dataset_path: {dataset_name}\n"
        f"results_path: {PACKAGE_FILENAMES['results']}\n"
        f"manifest_path: {PACKAGE_FILENAMES['manifest']}\n"
        f"trial_ledger_path: {PACKAGE_FILENAMES['trial_ledger']}\n"
        "# The last instant your research was allowed to observe.\n"
        f"evaluation_cutoff_utc: {evaluation_cutoff_utc!r}\n"
        f"timestamp_column: {timestamp_column}\n"
        "# Row ordering is checked within each instrument, not across the file.\n"
        f"symbol_column: {symbol_column}\n"
        "required_columns:\n"
        f"  - {timestamp_column}\n"
        f"  - {symbol_column}\n"
    )


def initialize_package(
    package_dir: str | Path,
    *,
    dataset_name: str,
    evaluation_cutoff_utc: str,
    timestamp_column: str = "timestamp",
    symbol_column: str = "symbol",
) -> tuple[tuple[Path, ...], tuple[str, ...]]:
    """Write config, manifest, results, and ledger templates beside a dataset.

    Returns the files created and the fields the customer must still fill in.
    Raises rather than overwriting anything that already exists.
    """
    directory = Path(package_dir).resolve(strict=True)
    if not directory.is_dir():
        raise ValueError("package_dir must be a directory")
    if not evaluation_cutoff_utc.strip():
        raise ValueError("evaluation_cutoff_utc is required")
    if Path(dataset_name).name != dataset_name:
        raise ValueError("dataset_name must be a file name inside package_dir, not a path")
    dataset = directory / dataset_name
    if not dataset.is_file():
        raise ValueError(f"{dataset_name} was not found in {directory}")
    if dataset.suffix.lower() not in _DATASET_SUFFIXES:
        allowed = ", ".join(sorted(_DATASET_SUFFIXES))
        raise ValueError(f"dataset format is not allowed; expected one of {allowed}")

    targets = _package_paths(directory)
    existing = sorted(str(path.name) for path in targets.values() if path.exists())
    if existing:
        raise FileExistsError(
            f"refusing to overwrite existing package files: {', '.join(existing)}"
        )

    digest = sha256_of_file(dataset)
    ledger_path = atomic_write_json(targets["trial_ledger"], _empty_ledger(), pretty=True)
    manifest_path = atomic_write_json(
        targets["manifest"], _manifest(dataset, digest, evaluation_cutoff_utc), pretty=True
    )
    results_path = atomic_write_json(
        targets["results"], _results(digest, sha256_of_file(ledger_path)), pretty=True
    )
    config_path = atomic_write_text(
        targets["config"],
        _config_text(
            dataset_name=dataset_name,
            evaluation_cutoff_utc=evaluation_cutoff_utc,
            timestamp_column=timestamp_column,
            symbol_column=symbol_column,
        ),
    )
    return (config_path, manifest_path, results_path, ledger_path), REQUIRED_PLACEHOLDERS


__all__ = [
    "PACKAGE_FILENAMES",
    "PLACEHOLDER",
    "REQUIRED_PLACEHOLDERS",
    "initialize_package",
]
