"""Optional, in-memory PNG rendering for SVG cards generated by Rigor."""

from __future__ import annotations

from typing import cast


def card_png(svg: str) -> bytes | None:
    """Render trusted card markup; missing Cairo or conversion failure is optional.

    No paths or output files are passed to CairoSVG. Callers must provide only
    server-generated markup, never uploaded SVG or arbitrary remote content.
    """
    try:
        import cairosvg

        return cast(bytes, cairosvg.svg2png(bytestring=svg.encode("utf-8")))
    except Exception:
        # The page and SVG remain usable even if an optional native renderer
        # cannot load or rejects a card. Never expose library error text.
        return None
